#!/bin/bash
# Just a small wrapper around find to avoid some common stuff I don't care
# about.

# TODO: Do something smarter to list dirs I don't care about
find "$@" 2>/dev/null | grep -v '.git' | grep -v '.svn'
